version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /research-kit
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /benchmarks/win32-min
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /benchmarks/windows-sys
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /benchmarks/windows
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
