//! Feature `security-descriptor` — ACL and security-descriptor primitives.
//!
//! The functions here expose raw Win32 ownership rules. In particular, buffers
//! returned by the SDDL conversion and `Get*SecurityInfo` APIs must be released
//! with [`LocalFree`]. Safe ownership belongs in a higher-level companion crate.

use crate::foundation::{BOOL, HANDLE, PCWSTR, PWSTR};
use core::ffi::c_void;

/// Opaque pointer to a SID.
pub type PSID = *mut c_void;
/// Opaque pointer to an absolute or self-relative security descriptor.
pub type PSECURITY_DESCRIPTOR = *mut c_void;
/// Handle to memory allocated by the Windows local allocator.
pub type HLOCAL = *mut c_void;
/// Bitmask stored in a security descriptor's control field.
pub type SECURITY_DESCRIPTOR_CONTROL = u16;
/// Bitmask selecting security descriptor components.
pub type SECURITY_INFORMATION = u32;
/// Access-mask type used by ACL and access-check APIs.
pub type ACCESS_MASK = u32;

/// Null SID pointer.
pub const NULL_PSID: PSID = core::ptr::null_mut();
/// Null ACL pointer.
pub const NULL_PACL: *mut ACL = core::ptr::null_mut();
/// Null security-descriptor pointer.
pub const NULL_SECURITY_DESCRIPTOR: PSECURITY_DESCRIPTOR = core::ptr::null_mut();

/// Current security descriptor revision.
pub const SECURITY_DESCRIPTOR_REVISION: u32 = 1;
/// Current SDDL revision.
pub const SDDL_REVISION_1: u32 = 1;

// SECURITY_DESCRIPTOR_CONTROL flags (winnt.h).
/// Owner SID came from a defaulting mechanism.
pub const SE_OWNER_DEFAULTED: SECURITY_DESCRIPTOR_CONTROL = 0x0001;
/// Primary group SID came from a defaulting mechanism.
pub const SE_GROUP_DEFAULTED: SECURITY_DESCRIPTOR_CONTROL = 0x0002;
/// A DACL is present, including a present-but-null DACL.
pub const SE_DACL_PRESENT: SECURITY_DESCRIPTOR_CONTROL = 0x0004;
/// DACL came from a defaulting mechanism.
pub const SE_DACL_DEFAULTED: SECURITY_DESCRIPTOR_CONTROL = 0x0008;
/// A SACL is present, including a present-but-null SACL.
pub const SE_SACL_PRESENT: SECURITY_DESCRIPTOR_CONTROL = 0x0010;
/// SACL came from a defaulting mechanism.
pub const SE_SACL_DEFAULTED: SECURITY_DESCRIPTOR_CONTROL = 0x0020;
/// DACL inheritance is requested.
pub const SE_DACL_AUTO_INHERIT_REQ: SECURITY_DESCRIPTOR_CONTROL = 0x0100;
/// SACL inheritance is requested.
pub const SE_SACL_AUTO_INHERIT_REQ: SECURITY_DESCRIPTOR_CONTROL = 0x0200;
/// DACL was generated by automatic inheritance.
pub const SE_DACL_AUTO_INHERITED: SECURITY_DESCRIPTOR_CONTROL = 0x0400;
/// SACL was generated by automatic inheritance.
pub const SE_SACL_AUTO_INHERITED: SECURITY_DESCRIPTOR_CONTROL = 0x0800;
/// DACL is protected from inheritance.
pub const SE_DACL_PROTECTED: SECURITY_DESCRIPTOR_CONTROL = 0x1000;
/// SACL is protected from inheritance.
pub const SE_SACL_PROTECTED: SECURITY_DESCRIPTOR_CONTROL = 0x2000;
/// Component fields contain offsets rather than absolute pointers.
pub const SE_SELF_RELATIVE: SECURITY_DESCRIPTOR_CONTROL = 0x8000;

// SECURITY_INFORMATION flags (winnt.h).
/// Select owner security information.
pub const OWNER_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x0000_0001;
/// Select primary-group security information.
pub const GROUP_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x0000_0002;
/// Select discretionary ACL security information.
pub const DACL_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x0000_0004;
/// Select system ACL security information.
pub const SACL_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x0000_0008;
/// Select mandatory integrity label information.
pub const LABEL_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x0000_0010;
/// Select resource-attribute information.
pub const ATTRIBUTE_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x0000_0020;
/// Select central-access-policy scope information.
pub const SCOPE_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x0000_0040;
/// Select process trust-label information.
pub const PROCESS_TRUST_LABEL_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x0000_0080;
/// Select access-filter information.
pub const ACCESS_FILTER_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x0000_0100;
/// Request backup/restore security-information semantics.
pub const BACKUP_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x0001_0000;
/// Remove SACL inheritance protection.
pub const UNPROTECTED_SACL_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x1000_0000;
/// Remove DACL inheritance protection.
pub const UNPROTECTED_DACL_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x2000_0000;
/// Protect the SACL from inheritance.
pub const PROTECTED_SACL_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x4000_0000;
/// Protect the DACL from inheritance.
pub const PROTECTED_DACL_SECURITY_INFORMATION: SECURITY_INFORMATION = 0x8000_0000;

/// Access-allowed ACE type identifier.
pub const ACCESS_ALLOWED_ACE_TYPE: u8 = 0x00;
/// Access-denied ACE type identifier.
pub const ACCESS_DENIED_ACE_TYPE: u8 = 0x01;
/// Object-inherit ACE flag.
pub const OBJECT_INHERIT_ACE: u8 = 0x01;
/// Container-inherit ACE flag.
pub const CONTAINER_INHERIT_ACE: u8 = 0x02;
/// Do-not-propagate ACE flag.
pub const NO_PROPAGATE_INHERIT_ACE: u8 = 0x04;
/// Inherit-only ACE flag.
pub const INHERIT_ONLY_ACE: u8 = 0x08;
/// Inherited ACE flag.
pub const INHERITED_ACE: u8 = 0x10;

/// Object kinds accepted by the `Get*SecurityInfo` family.
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SE_OBJECT_TYPE {
    /// Unknown or unspecified object type.
    SE_UNKNOWN_OBJECT_TYPE = 0,
    /// File or directory object.
    SE_FILE_OBJECT = 1,
    /// Windows service object.
    SE_SERVICE = 2,
    /// Printer object.
    SE_PRINTER = 3,
    /// Registry key.
    SE_REGISTRY_KEY = 4,
    /// Network share.
    SE_LMSHARE = 5,
    /// Kernel object such as a process, thread, or file handle.
    SE_KERNEL_OBJECT = 6,
    /// Window-station or desktop object.
    SE_WINDOW_OBJECT = 7,
    /// Directory Service object.
    SE_DS_OBJECT = 8,
    /// Directory Service object and all property sets.
    SE_DS_OBJECT_ALL = 9,
    /// Provider-defined object.
    SE_PROVIDER_DEFINED_OBJECT = 10,
    /// WMI GUID object.
    SE_WMIGUID_OBJECT = 11,
    /// Registry key forced to the 32-bit view.
    SE_REGISTRY_WOW64_32KEY = 12,
    /// Registry key forced to the 64-bit view.
    SE_REGISTRY_WOW64_64KEY = 13,
}

/// Fixed header of a Windows ACL.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct ACL {
    /// ACL revision.
    pub AclRevision: u8,
    /// Reserved byte.
    pub Sbz1: u8,
    /// Total ACL size in bytes.
    pub AclSize: u16,
    /// Number of ACE records.
    pub AceCount: u16,
    /// Reserved word.
    pub Sbz2: u16,
}

/// Header common to every ACE variant.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct ACE_HEADER {
    /// ACE type identifier.
    pub AceType: u8,
    /// Inheritance and audit flags.
    pub AceFlags: u8,
    /// Total ACE size in bytes.
    pub AceSize: u16,
}

/// Access-allowed ACE with the first SID word embedded at the tail.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct ACCESS_ALLOWED_ACE {
    /// Common ACE header.
    pub Header: ACE_HEADER,
    /// Rights granted by this ACE.
    pub Mask: ACCESS_MASK,
    /// First word of the variable-length SID.
    pub SidStart: u32,
}

/// Access-denied ACE with the first SID word embedded at the tail.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct ACCESS_DENIED_ACE {
    /// Common ACE header.
    pub Header: ACE_HEADER,
    /// Rights denied by this ACE.
    pub Mask: ACCESS_MASK,
    /// First word of the variable-length SID.
    pub SidStart: u32,
}

/// Six-byte SID authority identifier.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SID_IDENTIFIER_AUTHORITY {
    /// Big-endian authority value.
    pub Value: [u8; 6],
}

/// Variable-length SID header with space for its first sub-authority.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct SID {
    /// SID format revision.
    pub Revision: u8,
    /// Number of sub-authorities present.
    pub SubAuthorityCount: u8,
    /// Identifier authority.
    pub IdentifierAuthority: SID_IDENTIFIER_AUTHORITY,
    /// First element of the variable-length sub-authority array.
    pub SubAuthority: [u32; 1],
}

/// Absolute security descriptor whose component fields are pointers.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct SECURITY_DESCRIPTOR {
    /// Security descriptor revision.
    pub Revision: u8,
    /// Reserved byte.
    pub Sbz1: u8,
    /// Descriptor control flags.
    pub Control: SECURITY_DESCRIPTOR_CONTROL,
    /// Owner SID pointer.
    pub Owner: PSID,
    /// Primary group SID pointer.
    pub Group: PSID,
    /// System ACL pointer.
    pub Sacl: *mut ACL,
    /// Discretionary ACL pointer.
    pub Dacl: *mut ACL,
}

/// Generic-to-object-specific access-mask mapping.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GENERIC_MAPPING {
    /// Object rights corresponding to generic read.
    pub GenericRead: ACCESS_MASK,
    /// Object rights corresponding to generic write.
    pub GenericWrite: ACCESS_MASK,
    /// Object rights corresponding to generic execute.
    pub GenericExecute: ACCESS_MASK,
    /// Object rights corresponding to generic all.
    pub GenericAll: ACCESS_MASK,
}

/// Locally unique privilege identifier plus attributes.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LUID_AND_ATTRIBUTES {
    /// Privilege identifier.
    pub Luid: crate::foundation::LUID,
    /// Privilege attribute flags.
    pub Attributes: u32,
}

/// Variable-length privilege set with space for one privilege.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct PRIVILEGE_SET {
    /// Number of valid entries in `Privilege`.
    pub PrivilegeCount: u32,
    /// Privilege evaluation control flags.
    pub Control: u32,
    /// First element of the variable-length privilege array.
    pub Privilege: [LUID_AND_ATTRIBUTES; 1],
}

/// Self-relative security descriptor header. Offset fields are byte offsets
/// from the beginning of the descriptor, not pointers.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct SECURITY_DESCRIPTOR_RELATIVE {
    /// Descriptor revision.
    pub Revision: u8,
    /// Reserved byte.
    pub Sbz1: u8,
    /// Descriptor control flags including [`SE_SELF_RELATIVE`].
    pub Control: SECURITY_DESCRIPTOR_CONTROL,
    /// Byte offset of the owner SID, or zero.
    pub Owner: u32,
    /// Byte offset of the group SID, or zero.
    pub Group: u32,
    /// Byte offset of the SACL, or zero.
    pub Sacl: u32,
    /// Byte offset of the DACL, or zero.
    pub Dacl: u32,
}

#[link(name = "advapi32")]
extern "system" {
    /// Parses SDDL into a self-relative security descriptor.
    ///
    /// # Safety
    ///
    /// The SDDL pointer must be readable and null-terminated.
    /// `SecurityDescriptor` must be writable; the returned allocation is owned
    /// by the caller and must be released with [`LocalFree`]. The optional size
    /// output must be writable when non-null.
    pub fn ConvertStringSecurityDescriptorToSecurityDescriptorW(
        StringSecurityDescriptor: PCWSTR,
        StringSDRevision: u32,
        SecurityDescriptor: *mut PSECURITY_DESCRIPTOR,
        SecurityDescriptorSize: *mut u32,
    ) -> BOOL;

    /// Renders selected descriptor components as SDDL.
    ///
    /// # Safety
    ///
    /// The input descriptor must be valid. Both output pointers must be
    /// writable. The returned string allocation is owned by the caller and
    /// must be released with [`LocalFree`].
    pub fn ConvertSecurityDescriptorToStringSecurityDescriptorW(
        SecurityDescriptor: PSECURITY_DESCRIPTOR,
        RequestedStringSDRevision: u32,
        SecurityInformation: SECURITY_INFORMATION,
        StringSecurityDescriptor: *mut PWSTR,
        StringSecurityDescriptorLen: *mut u32,
    ) -> BOOL;

    /// Retrieves selected security information for a named object.
    ///
    /// # Safety
    ///
    /// The name must be a valid writable-compatible null-terminated UTF-16
    /// pointer. Each requested output must be writable. The descriptor output
    /// owns one local allocation; component pointers borrow from it and become
    /// invalid after [`LocalFree`]. Unrequested outputs may be null.
    pub fn GetNamedSecurityInfoW(
        pObjectName: PWSTR,
        ObjectType: SE_OBJECT_TYPE,
        SecurityInfo: SECURITY_INFORMATION,
        ppsidOwner: *mut PSID,
        ppsidGroup: *mut PSID,
        ppDacl: *mut *mut ACL,
        ppSacl: *mut *mut ACL,
        ppSecurityDescriptor: *mut PSECURITY_DESCRIPTOR,
    ) -> u32;

    /// Updates selected security information for a named object.
    ///
    /// # Safety
    ///
    /// The name and every component selected by `SecurityInfo` must point to
    /// valid storage for the duration of the call. Null component pointers are
    /// meaningful only where the Windows API permits them. The call mutates
    /// persistent object security.
    pub fn SetNamedSecurityInfoW(
        pObjectName: PWSTR,
        ObjectType: SE_OBJECT_TYPE,
        SecurityInfo: SECURITY_INFORMATION,
        psidOwner: PSID,
        psidGroup: PSID,
        pDacl: *mut ACL,
        pSacl: *mut ACL,
    ) -> u32;

    /// Retrieves selected security information for an object handle.
    ///
    /// # Safety
    ///
    /// `handle` must be valid with the required security access. Each requested
    /// output must be writable. The descriptor output owns one local allocation
    /// and its component outputs borrow from that allocation.
    pub fn GetSecurityInfo(
        handle: HANDLE,
        ObjectType: SE_OBJECT_TYPE,
        SecurityInfo: SECURITY_INFORMATION,
        ppsidOwner: *mut PSID,
        ppsidGroup: *mut PSID,
        ppDacl: *mut *mut ACL,
        ppSacl: *mut *mut ACL,
        ppSecurityDescriptor: *mut PSECURITY_DESCRIPTOR,
    ) -> u32;

    /// Updates selected security information for an object handle.
    ///
    /// # Safety
    ///
    /// The handle must be valid with the required write access, and every
    /// selected SID or ACL pointer must remain valid for the call. The caller
    /// is responsible for the security impact of the mutation.
    pub fn SetSecurityInfo(
        handle: HANDLE,
        ObjectType: SE_OBJECT_TYPE,
        SecurityInfo: SECURITY_INFORMATION,
        psidOwner: PSID,
        psidGroup: PSID,
        pDacl: *mut ACL,
        pSacl: *mut ACL,
    ) -> u32;

    /// Checks whether a security descriptor is structurally valid.
    ///
    /// # Safety
    ///
    /// `pSecurityDescriptor` must point to readable descriptor storage large
    /// enough for all offsets or pointers described by its format.
    pub fn IsValidSecurityDescriptor(pSecurityDescriptor: PSECURITY_DESCRIPTOR) -> BOOL;

    /// Returns a valid security descriptor's size in bytes.
    ///
    /// # Safety
    ///
    /// `pSecurityDescriptor` must point to a readable valid descriptor.
    pub fn GetSecurityDescriptorLength(pSecurityDescriptor: PSECURITY_DESCRIPTOR) -> u32;

    /// Retrieves the discretionary ACL pointer from a security descriptor.
    ///
    /// # Safety
    ///
    /// `pSecurityDescriptor` must point to a valid descriptor for the call.
    /// All three output pointers must be valid and writable. The returned ACL
    /// pointer borrows storage owned by the descriptor and must not be freed.
    pub fn GetSecurityDescriptorDacl(
        pSecurityDescriptor: PSECURITY_DESCRIPTOR,
        lpbDaclPresent: *mut BOOL,
        pDacl: *mut *mut ACL,
        lpbDaclDefaulted: *mut BOOL,
    ) -> BOOL;

    /// Retrieves the owner SID pointer from a security descriptor.
    ///
    /// # Safety
    ///
    /// The descriptor and both writable output pointers must be valid. The SID
    /// pointer borrows descriptor-owned storage and must not outlive it.
    pub fn GetSecurityDescriptorOwner(
        pSecurityDescriptor: PSECURITY_DESCRIPTOR,
        pOwner: *mut PSID,
        lpbOwnerDefaulted: *mut BOOL,
    ) -> BOOL;

    /// Retrieves the primary-group SID pointer from a security descriptor.
    ///
    /// # Safety
    ///
    /// The descriptor and both writable output pointers must be valid. The SID
    /// pointer borrows descriptor-owned storage and must not outlive it.
    pub fn GetSecurityDescriptorGroup(
        pSecurityDescriptor: PSECURITY_DESCRIPTOR,
        pGroup: *mut PSID,
        lpbGroupDefaulted: *mut BOOL,
    ) -> BOOL;

    /// Retrieves the system ACL pointer from a security descriptor.
    ///
    /// # Safety
    ///
    /// The descriptor and all three writable output pointers must be valid.
    /// The returned ACL pointer borrows descriptor-owned storage.
    pub fn GetSecurityDescriptorSacl(
        pSecurityDescriptor: PSECURITY_DESCRIPTOR,
        lpbSaclPresent: *mut BOOL,
        pSacl: *mut *mut ACL,
        lpbSaclDefaulted: *mut BOOL,
    ) -> BOOL;

    /// Initializes caller-owned storage as an absolute security descriptor.
    ///
    /// # Safety
    ///
    /// `pSecurityDescriptor` must point to writable storage large enough for
    /// [`SECURITY_DESCRIPTOR`] and remain valid for the call. `dwRevision`
    /// must be a supported descriptor revision.
    pub fn InitializeSecurityDescriptor(
        pSecurityDescriptor: PSECURITY_DESCRIPTOR,
        dwRevision: u32,
    ) -> BOOL;

    /// Assigns the DACL fields of an absolute security descriptor.
    ///
    /// # Safety
    ///
    /// `pSecurityDescriptor` must point to a valid writable absolute
    /// descriptor. A non-null `pDacl` must remain valid for at least as long as
    /// the descriptor is used; this function does not copy or own the ACL.
    pub fn SetSecurityDescriptorDacl(
        pSecurityDescriptor: PSECURITY_DESCRIPTOR,
        bDaclPresent: BOOL,
        pDacl: *mut ACL,
        bDaclDefaulted: BOOL,
    ) -> BOOL;

    /// Assigns the owner SID of an absolute security descriptor.
    ///
    /// # Safety
    ///
    /// The descriptor must be valid and writable. A non-null `pOwner` must
    /// point to a valid SID that outlives every use of the descriptor; the SID
    /// is borrowed and is not copied or freed by this function.
    pub fn SetSecurityDescriptorOwner(
        pSecurityDescriptor: PSECURITY_DESCRIPTOR,
        pOwner: PSID,
        bOwnerDefaulted: BOOL,
    ) -> BOOL;

    /// Assigns the primary-group SID of an absolute security descriptor.
    ///
    /// # Safety
    ///
    /// The descriptor must be valid and writable. A non-null `pGroup` must
    /// point to a valid SID that outlives every use of the descriptor; the SID
    /// is borrowed and is not copied or freed by this function.
    pub fn SetSecurityDescriptorGroup(
        pSecurityDescriptor: PSECURITY_DESCRIPTOR,
        pGroup: PSID,
        bGroupDefaulted: BOOL,
    ) -> BOOL;

    /// Tests an impersonation token against a security descriptor.
    ///
    /// # Safety
    ///
    /// The descriptor, token handle, mapping, length, granted-access, and
    /// access-status pointers must be valid. `PrivilegeSet` may be null only
    /// for a size query; otherwise it must provide `*PrivilegeSetLength` bytes
    /// of writable storage. All pointed-to values must live through the call.
    pub fn AccessCheck(
        pSecurityDescriptor: PSECURITY_DESCRIPTOR,
        ClientToken: HANDLE,
        DesiredAccess: u32,
        GenericMapping: *mut GENERIC_MAPPING,
        PrivilegeSet: *mut PRIVILEGE_SET,
        PrivilegeSetLength: *mut u32,
        GrantedAccess: *mut u32,
        AccessStatus: *mut BOOL,
    ) -> BOOL;
}

#[link(name = "kernel32")]
extern "system" {
    /// Frees memory allocated by a Windows local-allocation API.
    ///
    /// # Safety
    ///
    /// `hMem` must be null or an allocation whose documented release function
    /// is `LocalFree`, must not already be freed, and must be uniquely owned.
    pub fn LocalFree(hMem: HLOCAL) -> HLOCAL;
}

const _: () = {
    assert!(core::mem::size_of::<ACL>() == 8);
    assert!(core::mem::align_of::<ACL>() == 2);
    assert!(core::mem::size_of::<ACE_HEADER>() == 4);
    assert!(core::mem::align_of::<ACE_HEADER>() == 2);
    assert!(core::mem::size_of::<SECURITY_DESCRIPTOR_RELATIVE>() == 20);
    assert!(core::mem::align_of::<SECURITY_DESCRIPTOR_RELATIVE>() == 4);
    assert!(core::mem::size_of::<ACCESS_ALLOWED_ACE>() == 12);
    assert!(core::mem::size_of::<ACCESS_DENIED_ACE>() == 12);
    assert!(core::mem::size_of::<SID_IDENTIFIER_AUTHORITY>() == 6);
    assert!(core::mem::size_of::<SID>() == 12);
    assert!(core::mem::size_of::<GENERIC_MAPPING>() == 16);
    assert!(core::mem::size_of::<LUID_AND_ATTRIBUTES>() == 12);
    assert!(core::mem::size_of::<PRIVILEGE_SET>() == 20);
};

#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(core::mem::size_of::<SECURITY_DESCRIPTOR>() == 40);
    assert!(core::mem::align_of::<SECURITY_DESCRIPTOR>() == 8);
};

#[cfg(target_pointer_width = "32")]
const _: () = {
    assert!(core::mem::size_of::<SECURITY_DESCRIPTOR>() == 20);
    assert!(core::mem::align_of::<SECURITY_DESCRIPTOR>() == 4);
};
